-- Create custom user
CREATE USER expense WITH PASSWORD 'Admin@123';

-- Create database owned by expense
CREATE DATABASE expensetracker OWNER expense;

-- Grant privileges on database
GRANT CONNECT ON DATABASE expensetracker TO expense;

-- Connect to expensetracker
\c expensetracker;

-- Grant schema privileges
GRANT USAGE ON SCHEMA public TO expense;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO expense;
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO expense;

-- Create table 'entry'
CREATE TABLE public.entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DOUBLE PRECISION NOT NULL,
    date DATE,
    description VARCHAR(255),
    type VARCHAR(255)
);
