GRANT CONNECT ON DATABASE expensetracker TO expense;
GRANT USAGE ON SCHEMA public TO expense;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO expense;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO expense;
